resources:
- name: tutorial
  type: git
  source:
    uri: https://github.com/nwiizo/test_docker_image_resource.git
    branch: master

- name: hello-world-docker-image
  type: docker-image
  source:
    email: <usermail>
    username: <username>
    password: <password>
    repository: <username>/concourse-tutorial-hello-world

jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: tutorial
  - put: hello-world-docker-image
    params:
      # tutorial -> get: tutorial
      build: tutorial/docker
  - task: run
    config:
      platform: linux
      image_resource:
         type: docker-image
         source:
           repository: <username>/concourse-tutorial-hello-world
      run:
        path: /bin/hello-world
        args: []
    params:
      NAME: <username>
